# Generated by Django 5.0.6 on 2026-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=16)),
                ('ts', models.DateTimeField(db_index=True)),
                ('verdict', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('user_agent', models.TextField(blank=True)),
                ('is_headless', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['public_id', 'ts'], name='analytics_c_public__4f77fd_idx')],
            },
        ),
    ]
