# Generated by Django 5.0.6 on 2026-09-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_longer_slug'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='website',
            field=models.ForeignKey(blank=True, help_text="Optional — which site's Traffic Rules apply to clicks.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_links', to='websites.website'),
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reported_url', models.CharField(max_length=2000)),
                ('reason', models.CharField(choices=[('phishing', 'Phishing / fake login page'), ('malware', 'Malware or harmful download'), ('spam', 'Spam (unsolicited email or SMS)'), ('scam', 'Scam or fraud'), ('other', 'Something else')], default='phishing', max_length=16)),
                ('details', models.TextField(blank=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('actioned', 'Actioned — link disabled'), ('dismissed', 'Dismissed — no action needed')], db_index=True, default='new', max_length=12)),
                ('auto_disabled', models.BooleanField(default=False, help_text='The threat scan triggered by this report disabled the link.')),
                ('scan_result', models.JSONField(blank=True, default=dict, help_text='Threat scan run at the moment the report arrived.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='links.shortlink')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='links_abuse_status_089b68_idx')],
            },
        ),
    ]
