# Generated by Django 5.0.6 on 2026-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_shortlink_website_abusereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='challenge',
            field=models.BooleanField(default=False, help_text="Ask visitors to confirm they're human before redirecting."),
        ),
    ]
