# Generated by Django 5.0.6 on 2026-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_shortlink_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='forward_params',
            field=models.BooleanField(default=False, help_text="Forward the link's query string on to the destination."),
        ),
    ]
