# Generated by Django 5.0.6 on 2026-09-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_shortlink_forward_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='forward_param_keys',
            field=models.CharField(blank=True, default='', help_text='Only forward these parameters, e.g. "email,rid". Blank = all.', max_length=300),
        ),
    ]
