# Generated by Django 5.0.6 on 2026-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_shortlink_forward_param_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='block_vpn',
            field=models.BooleanField(default=False, help_text='Give VPN, proxy and datacenter/RDP visitors the bot handling.'),
        ),
    ]
