# Generated by Django 5.0.6 on 2026-09-06 10:29

import apps.links.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_shortlink_block_vpn'),
        ('organizations', '0001_initial'),
        ('websites', '0002_strict_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.SlugField(default=apps.links.models.gen_slug, max_length=64),
        ),
        migrations.CreateModel(
            name='ShortDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Bare hostname, e.g. "trynb.cc" — no scheme, no trailing slash.', max_length=190, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to retire a domain; its links stop resolving.')),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected when creating a redirect.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Our own domains are verified on creation.', null=True)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Empty = available to every workspace (our own domain).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_domains', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort', 'host'],
            },
        ),
        migrations.AddField(
            model_name='shortlink',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='links.shortdomain'),
        ),
        migrations.AddConstraint(
            model_name='shortlink',
            constraint=models.UniqueConstraint(fields=('domain', 'slug'), name='uniq_slug_per_domain'),
        ),
    ]
