# Generated by Django 5.0.6 on 2026-09-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_backfill_short_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='challenge_style',
            field=models.CharField(choices=[('hold', 'Press and hold (5 seconds)'), ('checkbox', 'Tick a box'), ('slide', 'Slide to continue')], default='hold', max_length=10),
        ),
    ]
