# Generated by Django 5.0.6 on 2026-09-08 21:37

import apps.links.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_challenge_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusereport',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='slug',
            field=models.SlugField(default=apps.links.models.gen_slug, max_length=200),
        ),
    ]
