# Generated by Django 5.0.6 on 2026-09-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_longer_slugs'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdomain',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='In the pool everyone can use. Uncheck for stock held back to sell privately.'),
        ),
        migrations.AlterField(
            model_name='shortdomain',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set = private to that workspace. Empty = shared, or unsold stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_domains', to='organizations.organization'),
        ),
    ]
