# Generated by Django 5.0.6 on 2026-09-10 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_private_domains'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDomainPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='USD charged.')),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid — awaiting a domain'), ('fulfilled', 'Domain assigned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('bachs_session_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='links.shortdomain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_domain_purchases', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_domain_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
