# Generated by Django 5.0.6 on 2026-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_private_domain_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdomain',
            name='private_until',
            field=models.DateTimeField(blank=True, help_text='Paid through this date. Only meaningful for a private domain.', null=True),
        ),
    ]
