# Generated by Django 5.0.6 on 2026-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_private_domain_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='countries',
            field=models.CharField(blank=True, default='', help_text='Comma-separated ISO-2 codes, e.g. "US,CA,GB".', max_length=400),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='country_mode',
            field=models.CharField(choices=[('off', 'Everywhere'), ('allow', 'Only these countries'), ('block', 'Everywhere except these')], default='off', max_length=6),
        ),
    ]
