# Generated by Django 5.0.6 on 2026-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0016_country_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='device_mode',
            field=models.CharField(choices=[('off', 'Everywhere'), ('allow', 'Only these countries'), ('block', 'Everywhere except these')], default='off', max_length=6),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='devices',
            field=models.CharField(blank=True, default='', help_text='Comma-separated: mobile, desktop, tablet', max_length=100),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='max_risk',
            field=models.IntegerField(default=0, help_text='Refuse visitors at or above this risk score (0 = off).'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='operating_systems',
            field=models.CharField(blank=True, default='', help_text='Comma-separated: windows, macos, ios, android, linux', max_length=200),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='os_mode',
            field=models.CharField(choices=[('off', 'Everywhere'), ('allow', 'Only these countries'), ('block', 'Everywhere except these')], default='off', max_length=6),
        ),
    ]
