# Generated by Django 5.0.6 on 2026-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0017_simple_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='decoy_url',
            field=models.URLField(blank=True, default='', help_text='Send bots to your own page instead of the built-in decoy. Blank = built-in.'),
        ),
    ]
