# Generated by Django 5.0.6 on 2026-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0018_link_decoy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='scan_optout',
            field=models.BooleanField(default=False),
        ),
    ]
