# Generated by Django 5.0.6 on 2026-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0019_link_scan_optout'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='block_datacenter',
            field=models.BooleanField(default=False, help_text='Give datacenter/hosting visitors the bot handling (allows VPN).'),
        ),
    ]
