# Generated by Django 5.0.6 on 2026-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0020_block_datacenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='deep_check',
            field=models.BooleanField(default=False, help_text='Run a silent browser check before redirecting (catches headless bots).'),
        ),
    ]
