# Generated by Django 5.0.6 on 2026-09-13 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0021_deep_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedomainpurchase',
            name='renew_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='links.shortdomain'),
        ),
    ]
