# Generated by Django 5.0.6 on 2026-09-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0022_purchase_renew_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdomain',
            name='byod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shortdomain',
            name='verify_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
