# Generated by Django 5.0.6 on 2026-09-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0023_byod_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedomainpurchase',
            name='requested_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by', to='links.shortdomain'),
        ),
    ]
