# Generated by Django 5.0.6 on 2026-09-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0024_privatedomainpurchase_requested_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortdomain',
            name='health',
            field=models.CharField(choices=[('unknown', 'Not checked yet'), ('ok', 'Serving normally'), ('unreachable', 'DNS or HTTPS failed — possibly suspended'), ('flagged', 'Flagged by a safety scanner')], db_index=True, default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='shortdomain',
            name='health_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortdomain',
            name='health_detail',
            field=models.CharField(blank=True, default='', help_text='What the last check saw.', max_length=300),
        ),
    ]
