# Generated by Django 5.0.6 on 2026-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0025_shortdomain_health_shortdomain_health_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='reviewer_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
