# Generated by Django 5.0.6 on 2026-08-31 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.IntegerField(default=100, help_text='Lower runs first; first match wins')),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('block', 'Block'), ('tag', 'Tag')], default='review', max_length=8)),
                ('tag', models.CharField(blank=True, help_text='Label applied when action = Tag', max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('risk_score', 'Risk score'), ('classification', 'Classification'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'OS'), ('is_bot', 'Bot detected'), ('is_proxy', 'Proxy/Datacenter'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('referrer', 'Referrer')], max_length=20)),
                ('operator', models.CharField(choices=[('eq', 'equals'), ('ne', 'not equals'), ('gt', 'greater than'), ('gte', '≥'), ('lt', 'less than'), ('lte', '≤'), ('contains', 'contains'), ('in', 'in list')], max_length=8)),
                ('value', models.CharField(max_length=200)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.trafficrule')),
            ],
        ),
    ]
