# Generated by Django 5.0.6 on 2026-08-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='field',
            field=models.CharField(choices=[('risk_score', 'Risk score'), ('classification', 'Classification'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'OS'), ('is_bot', 'Bot detected'), ('is_proxy', 'Proxy/Datacenter'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('referrer', 'Referrer'), ('ja3', 'TLS/JA3 hash')], max_length=20),
        ),
        migrations.CreateModel(
            name='IPListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Exact IP or CIDR, e.g. 1.2.3.4 or 10.0.0.0/8', max_length=64)),
                ('kind', models.CharField(choices=[('allow', 'Allow (whitelist)'), ('deny', 'Deny (blacklist)')], default='deny', max_length=5)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_entries', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'value', 'kind')},
            },
        ),
    ]
