# Generated by Django 5.0.6 on 2026-08-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rulecondition_field_iplistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Where to send traffic when action = Redirect'),
        ),
        migrations.AlterField(
            model_name='trafficrule',
            name='action',
            field=models.CharField(choices=[('allow', 'Allow'), ('redirect', 'Redirect'), ('block', 'Block'), ('review', 'Review'), ('tag', 'Tag')], default='review', max_length=8),
        ),
    ]
