# Generated by Django 5.0.6 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_trafficrule_redirect_url_alter_trafficrule_action'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Which website this rule applies to. Empty = all websites in the workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_rules', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='field',
            field=models.CharField(choices=[('risk_score', 'Risk score'), ('requests_per_min', 'Requests/minute'), ('classification', 'Classification'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'OS'), ('is_bot', 'Bot detected'), ('is_proxy', 'Proxy/Datacenter'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('referrer', 'Referrer'), ('ja3', 'TLS/JA3 hash'), ('path', 'URL path')], max_length=20),
        ),
    ]
