# Generated by Django 5.0.6 on 2026-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rulecondition_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='field',
            field=models.CharField(choices=[('risk_score', 'Risk score'), ('requests_per_min', 'Requests/minute'), ('classification', 'Classification'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'OS'), ('is_bot', 'Bot detected'), ('is_proxy', 'Proxy / VPN / Datacenter (any)'), ('is_vpn', 'VPN or Tor'), ('is_datacenter', 'Datacenter / RDP'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('referrer', 'Referrer'), ('ja3', 'TLS/JA3 hash'), ('path', 'URL path')], max_length=20),
        ),
    ]
