# Generated by Django 5.0.6 on 2026-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_private_domain_rental'),
        ('rules', '0006_vpn_datacenter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='short_link',
            field=models.ForeignKey(blank=True, help_text='Which redirect this rule applies to. Empty = not a redirect rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='links.shortlink'),
        ),
    ]
