# Generated by Django 5.0.6 on 2026-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_deeper_signal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='field',
            field=models.CharField(choices=[('risk_score', 'Risk score'), ('requests_per_min', 'Requests/minute'), ('classification', 'Classification'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'OS'), ('is_bot', 'Bot detected'), ('is_proxy', 'Proxy / VPN / Datacenter (any)'), ('is_vpn', 'VPN or Tor'), ('is_datacenter', 'Datacenter / RDP'), ('connection_type', 'Connection type'), ('isp', 'ISP'), ('asn', 'ASN'), ('is_mobile', 'Mobile connection'), ('browser_version', 'Browser version'), ('os_version', 'OS version'), ('language', 'Browser language'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('referrer', 'Referrer'), ('ja3', 'TLS/JA3 hash'), ('ja4', 'TLS/JA4 hash'), ('path', 'URL path')], max_length=20),
        ),
    ]
