# Generated by Django 5.0.6 on 2026-08-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('destination_url', models.URLField(blank=True)),
                ('traffic_source', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('tiktok', 'TikTok'), ('bing', 'Bing'), ('native', 'Native'), ('organic', 'Organic'), ('direct', 'Direct'), ('other', 'Other')], default='other', max_length=16)),
                ('country', models.CharField(blank=True, help_text='ISO code, optional', max_length=2)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=120)),
                ('risk_threshold', models.IntegerField(default=70, help_text='Score at/above which traffic is flagged')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
