# Generated by Django 5.0.6 on 2026-08-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='url_safe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='url_threats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
