# Generated by Django 5.0.6 on 2026-08-31 14:41

import apps.websites.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(help_text='e.g. example.com', max_length=180)),
                ('url', models.URLField(blank=True)),
                ('tracking_id', models.CharField(db_index=True, default=apps.websites.models.gen_tracking_id, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('not_installed', 'Not installed'), ('detected', 'Detected'), ('active', 'Active'), ('error', 'Error')], default='not_installed', max_length=16)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
