# Generated by Django 5.0.6 on 2026-09-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='strict_mode',
            field=models.BooleanField(default=False, help_text='Hide the page until the bot check finishes (stops blocked visitors seeing content).'),
        ),
    ]
