# Generated by Django 5.0.6 on 2026-09-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_strict_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
