# Generated by Django 5.0.6 on 2026-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_system_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='safe_browsing_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='safe_browsing_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='safe_browsing_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='safe_browsing_threats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
