// GENERATED by frontend/scripts/encode-videos.sh — do not edit by hand.
//
// Walkthroughs whose VP9 encode came out smaller than the H.264 one, and so
// are worth offering ahead of the mp4. A name missing here is mp4-only.
export const HAS_WEBM: ReadonlySet<string> = new Set([
  "redirection",
  "shield",
]);
