# Generated by Django 5.0.6 on 2026-08-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('landing_url', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('os', models.CharField(blank=True, max_length=40)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='websites.website')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pageview', 'Pageview'), ('event', 'Custom event'), ('conversion', 'Conversion')], default='pageview', max_length=12)),
                ('url', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('event_name', models.CharField(blank=True, max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('os', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('is_headless', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traffic.session')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='websites.website')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traffic.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='traffic.visitor'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['website', 'last_seen'], name='traffic_vis_website_7f3b34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('website', 'visitor_id')},
        ),
        migrations.AddIndex(
            model_name='trafficevent',
            index=models.Index(fields=['website', 'created_at'], name='traffic_tra_website_f0ec3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('website', 'session_id')},
        ),
    ]
