# Generated by Django 5.0.6 on 2026-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='signals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
