# Generated by Django 5.0.6 on 2026-08-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_trafficevent_confidence_trafficevent_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='action',
            field=models.CharField(default='allow', max_length=8),
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='tag',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
