# Generated by Django 5.0.6 on 2026-08-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_trafficevent_action_trafficevent_tag'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='conversion', max_length=80)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='traffic.session')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='traffic.visitor')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['website', 'created_at'], name='traffic_con_website_f1c2cd_idx')],
            },
        ),
    ]
