# Generated by Django 5.0.6 on 2026-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='fp_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitor',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
