# Generated by Django 5.0.6 on 2026-08-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_trafficevent_fingerprint_trafficevent_fp_signals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='ja3',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
