# Generated by Django 5.0.6 on 2026-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_trafficevent_ja3'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='ja4',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
