# Generated by Django 5.0.6 on 2026-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_trafficevent_ja4'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='behaviour',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
