# Generated by Django 5.0.6 on 2026-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_trafficevent_behaviour'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficevent',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficevent',
            name='reviewer_platform',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
