# Generated by Django 5.0.6 on 2026-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_trafficevent_is_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ad_platform',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='session',
            name='is_paid_click',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
