# Generated by Django 5.0.6 on 2026-09-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JA4Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja4', models.CharField(help_text='JA4 fingerprint hash', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='What client this belongs to', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
