# Generated by Django 5.0.6 on 2026-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_ja4block'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCheckLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(help_text='The site they scanned.', max_length=2000)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('exposure', models.IntegerField(default=0, help_text='0-100 exposure score at scan time.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='intelligenc_email_00ac6f_idx')],
            },
        ),
    ]
