# Generated by Django 5.0.6 on 2026-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_botchecklead'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchecklead',
            name='followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
