# Generated by Django 5.0.6 on 2026-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_botchecklead_followup_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchecklead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
