# Generated by Django 5.0.6 on 2026-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bachs_product_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='subscription',
            name='bachs_session_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
