# Generated by Django 5.0.6 on 2026-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_plan_bachs_product_id_subscription_bachs_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
