# Generated by Django 5.0.6 on 2026-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_backfill_trial_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_campaigns',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_redirects',
            field=models.IntegerField(default=0, help_text='Short-link (redirect) cap (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_websites',
            field=models.IntegerField(default=0, help_text='Domains cap (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan_slug',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(help_text='USD per week'),
        ),
    ]
