# Generated by Django 5.0.6 on 2026-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_weekly_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bachs_product_id_monthly',
            field=models.CharField(blank=True, default='', help_text='Bachs product for the MONTHLY price.', max_length=80),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_monthly',
            field=models.IntegerField(default=0, help_text='USD per month (0 = monthly not offered)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_interval',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bachs_product_id',
            field=models.CharField(blank=True, default='', help_text='Bachs product for the WEEKLY price.', max_length=80),
        ),
    ]
