# Generated by Django 5.0.6 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_seed_monthly_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_redirects_monthly',
            field=models.IntegerField(default=0, help_text='Redirect cap on MONTHLY billing (0 = same as weekly)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_websites_monthly',
            field=models.IntegerField(default=0, help_text='Domains cap on MONTHLY billing (0 = same as weekly)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_redirects',
            field=models.IntegerField(default=0, help_text='Redirect cap on WEEKLY billing (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_websites',
            field=models.IntegerField(default=0, help_text='Domains cap on WEEKLY billing (0 = unlimited)'),
        ),
    ]
