# Generated by Django 5.0.6 on 2026-09-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_ad_click_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='notify_daily_limit',
            field=models.BigIntegerField(default=0, help_text='Inbound notifications per DAY on this plan (0 = unlimited)'),
        ),
    ]
