#!/bin/sh
# Refuse requests that reach the origin without passing through Cloudflare.
#
# Opt-in: set ORIGIN_CLOUDFLARE_ONLY=1 in .env. Off by default, because turning
# it on before EVERY domain is proxied (orange cloud) takes those sites down.
#
# Why bother: while the origin answers on its bare IP, anyone can ask it for
# trynb.cc and trynobot.com in turn and see the same server answer both — which
# links the short-link domain to the brand domain no matter how carefully the
# HTML avoids naming it. Blocking direct hits closes that.
#
# Done in nginx rather than the host firewall on purpose. Docker publishes
# :80/:443 by inserting its own iptables rules, which UFW never sees, so
# `ufw deny 80` looks like it worked and silently does nothing. Doing it here
# also can't lock anyone out of SSH.
set -e

INC=/etc/nginx/originlock.inc          # included inside each server block
CONF=/etc/nginx/conf.d/01-originlock.conf
: > "$INC"                             # default: empty, so nothing is blocked

case "${ORIGIN_CLOUDFLARE_ONLY:-0}" in
  1|true|yes|on) ;;
  *) exit 0 ;;
esac

RANGES=/etc/nginx/conf.d/00-cloudflare-realip.conf
if [ ! -f "$RANGES" ]; then
  echo "originlock: no Cloudflare ranges found — leaving the origin open."
  exit 0
fi

{
  echo "# Generated by 20-originlock.sh — ORIGIN_CLOUDFLARE_ONLY is on."
  echo "# Peer address BEFORE real_ip rewrites it: \$remote_addr is by then the"
  echo "# visitor's own IP, which would match nothing here."
  echo "geo \$realip_remote_addr \$cf_peer {"
  echo "    default 0;"
  # Reuse the same list real_ip trusts, so the two can never disagree.
  sed -n 's/^set_real_ip_from \(.*\);$/    \1 1;/p' "$RANGES"
  echo "}"
  echo
  echo "# Certificate renewal must survive this. A domain that isn't proxied yet"
  echo "# is validated by Let's Encrypt connecting to the origin directly, and"
  echo "# locking that out would fail issuance with no obvious cause."
  echo "map \$uri \$is_acme {"
  echo "    default 0;"
  echo "    ~^/\\.well-known/acme-challenge/ 1;"
  echo "}"
  echo
  echo "# Deny only when both are false: not from Cloudflare, not an ACME check."
  echo "map \"\$cf_peer\$is_acme\" \$deny_origin {"
  echo "    default 0;"
  echo "    \"00\" 1;"
  echo "}"
} > "$CONF"

# 444: close the connection without a response. A direct prober learns nothing
# about what this server hosts — an error page would still confirm it's here.
echo 'if ($deny_origin) { return 444; }' > "$INC"

echo "originlock: origin restricted to Cloudflare ($(grep -c ' 1;$' "$CONF") ranges)"
