# Generated by Django 5.0.6 on 2026-09-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False, help_text='Tick once someone has replied.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
