# Generated by Django 5.0.6 on 2026-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='link_scan_optout',
            field=models.BooleanField(default=False),
        ),
    ]
